version: "3.9"


services:
  web:
    container_name: web_frontend
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ".:/app"
    ports:
      - "8005:8005"
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  database:
    container_name: database
    image: "mysql:latest"
    restart: unless-stopped
    env_file: ./.env
    command: --authentication_policy=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
