name: Docker Test
on: [push]
jobs:
  Docker-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v2
      - name: Build web container
      - run: docker buid -t internet-privacy . & docker network create 397net
      - name: Print out a status report
        run: docker ps
      - name: Start up the web container
        run: docker run --rm --name priv-website --net 397net -d -p 80:80 internet-privacy
      - name: Test web navigation to docker web container
        run: curl -s --retry 3 --retry-connrefused http://localhost:80/
