name: GitHub Actions Demo
on: [push]
jobs:
  Test-Build-Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v2
      - name: Build containers using docker-compose
      - run: docker-compose up
      - run: echo "Docker-compose: ${{ job.status }}."
