name: GitHub Actions Demo
on: [push]
jobs:
  Test-Build-Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v2
      - name: Build containers using docker-compose
        run: docker-compose up -d
      - name: Test the docker web container
        run: docker run --network container:web_frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/
