name: GitHub Actions Demo
on: [push]
jobs:
  Test-Build-Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling repository
      - uses: actions/checkout@v2
      - name: Builds using docker-compose
      - run: docker-compose up
